# Generated by Django 4.0.4 on 2022-05-04 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_inputclass_inputclas'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Inputclas',
        ),
    ]
