# Generated by Django 4.0.4 on 2022-05-27 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_delete_inputclas'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClgInfoIntents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=140)),
                ('patterns', models.CharField(max_length=140)),
                ('responses', models.CharField(max_length=140)),
            ],
        ),
    ]
