# Generated by Django 4.0.4 on 2022-05-26 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_intents'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Intents',
        ),
    ]
