# Generated by Django 4.0.4 on 2022-05-26 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_intents'),
    ]

    operations = [
        migrations.RenameField(
            model_name='intents',
            old_name='pattern',
            new_name='patterns',
        ),
        migrations.RenameField(
            model_name='intents',
            old_name='response',
            new_name='responses',
        ),
    ]
