# Generated by Django 4.0.4 on 2022-05-27 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_clginfointents'),
        ('main', '0008_rename_pattern_intents_patterns_and_more'),
    ]

    operations = [
    ]
