# Generated by Django 4.0.4 on 2022-05-04 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_inputclass'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='inputclass',
            new_name='Inputclas',
        ),
    ]
